name: openmmlab
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - aiohappyeyeballs=2.4.0=py38haa95532_0
  - aiohttp=3.10.5=py38h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=16.1.0=h7cd61ee_0
  - async-timeout=4.0.3=py38haa95532_0
  - attrs=24.2.0=py38haa95532_0
  - aws-c-auth=0.6.19=h2bbff1b_0
  - aws-c-cal=0.5.20=h2bbff1b_0
  - aws-c-common=0.8.5=h2bbff1b_0
  - aws-c-compression=0.2.16=h2bbff1b_0
  - aws-c-event-stream=0.2.15=hd77b12b_0
  - aws-c-http=0.6.25=h2bbff1b_0
  - aws-c-io=0.13.10=h2bbff1b_0
  - aws-c-mqtt=0.7.13=h2bbff1b_0
  - aws-c-s3=0.1.51=h2bbff1b_0
  - aws-c-sdkutils=0.1.6=h2bbff1b_0
  - aws-checksums=0.1.13=h2bbff1b_0
  - aws-crt-cpp=0.18.16=hd77b12b_0
  - aws-sdk-cpp=1.10.55=hd77b12b_0
  - blas=1.0=mkl
  - boto3=1.34.154=py38haa95532_0
  - botocore=1.34.154=py38haa95532_0
  - bottleneck=1.3.7=py38h9128911_0
  - brotli-python=1.0.9=py38hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2024.8.30=py38haa95532_0
  - cffi=1.17.1=py38h827c3e9_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py38haa95532_0
  - cuda-cccl=12.4.127=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cudatoolkit=11.8.0=hd77b12b_0
  - datasets=2.12.0=py38haa95532_0
  - dill=0.3.6=py38haa95532_0
  - freetype=2.13.3=h0620614_0
  - frozenlist=1.4.0=py38h2bbff1b_0
  - fsspec=2024.6.1=py38haa95532_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - gmpy2=2.1.2=py38h7f96b67_0
  - huggingface_hub=0.24.6=py38haa95532_0
  - idna=3.7=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.4=py38haa95532_0
  - jpeg=9f=ha349fce_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20240116.2=cxx17_h5da7b33_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.17.0=h97e0424_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.62.2=hf25190f_0
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py38h2bbff1b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py38haa95532_0
  - multidict=6.0.4=py38h2bbff1b_0
  - multiprocess=0.70.14=py38haa95532_0
  - networkx=3.1=py38haa95532_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - orc=2.0.1=hd8d391b_0
  - pandas=2.0.3=py38h4ed8f06_0
  - pillow=10.4.0=py38h827c3e9_0
  - pip=24.2=py38haa95532_0
  - pyarrow=16.1.0=py38hc64d2fc_0
  - pyopenssl=24.2.1=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0post0=py38haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py38h2bbff1b_1
  - pytorch=2.1.0=py3.8_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py38h827c3e9_0
  - re2=2022.04.01=hd77b12b_0
  - responses=0.13.3=pyhd3eb1b0_0
  - s3transfer=0.10.1=py38haa95532_0
  - safetensors=0.4.5=py38h9e6c545_0
  - snappy=1.2.2=hab6b7b3_1
  - sqlite=3.51.1=hda9a48d_0
  - sympy=1.13.3=py38haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tokenizers=0.20.1=py38h5bc1c3f_0
  - transformers=4.45.2=py38haa95532_0
  - typing_extensions=4.11.0=py38haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.11.0=py38h827c3e9_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - addict==2.4.0
      - aio-pika==9.5.2
      - aiormq==6.8.1
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - chumpy==0.70
      - click==8.1.8
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.4
      - dotenv==0.9.9
      - exceptiongroup==1.3.1
      - filelock==3.14.0
      - fonttools==4.57.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jmespath==0.10.0
      - json-tricks==3.17.3
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.2.0
      - mmengine==0.10.7
      - mmpose==1.3.2
      - model-index==0.1.11
      - munkres==1.1.4
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pamqp==3.3.0
      - platformdirs==4.3.6
      - pycocotools==2.0.7
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dotenv==1.0.1
      - pytz==2023.4
      - pywin32==311
      - regex==2024.11.6
      - requests==2.28.2
      - rich==13.4.2
      - scipy==1.10.1
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tomli==2.4.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tqdm==4.65.2
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - urllib3==1.26.20
      - xtcocotools==1.14.3
      - yapf==0.43.0
      - zipp==3.20.2
      - aioboto3==14.3.0
